services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080/tcp
      - ${PANEL_APP_PORT_HTTP}:8080/udp
    volumes:
      - ./data:/root/.synctv
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=${TZ}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true